Add an option to whitelist GH organizations
appuri/kibana-oauth2-plugin pull request #2
Opened 2016-10-05 07:25 UTC by MiLk

2016-10-05 17:35 UTC, nathanboktae requested changes
Very useful PR. Can you also add documentation and fix the one code issue? Thanks!

2016-10-05 17:35 UTC, nathanboktae commented on index.js
> +            return;
You need to return the promise here so the handler is aware of your async work.

```javascript
return axios.get(....
```

2016-10-06 01:42 UTC, MiLk commented on index.js
> +            return;
I'm not familiar with hapi or the kibana plugin ecosystem.
It should be good now.

2016-10-06 01:43 UTC, MiLk commented
I've added the documentation.

If you make a release, please be sure to use npm 2 to make the build, as the gulpfile doesn't support npm 3 and the flat structure for dependencies.

The current build for 0.3.0 is not working for me. Dependencies are missing.

Thanks.

2016-10-07 17:00 UTC, nathanboktae approved these changes

2016-10-07 17:00 UTC, merged